import * as assert from "assert";
import * as vscode from "vscode";

import { WhitespaceQuickFixProvider } from "../../codeActions/whitespaceQuickFixes";
import { DIAGNOSTIC_CODES } from "../../constants";
import type { DiagnosticCode } from "../../types/diagnostics";

/**
 * Test suite for whitespace quick fixes.
 *
 * These tests validate that each CodeAction generated by the
 * WhitespaceQuickFixProvider applies the expected WorkspaceEdit to a Makefile
 * document.
 *
 * The tests focus on the final document content after the quick fix is applied,
 * ensuring that the edit behavior matches the diagnostic being fixed.
 */
suite("Whitespace quick fixes", () => {
  test("removes trailing whitespace", async () => {
    const document = await createMakefileDocument("NODE_VERSION := 22   \n");

    const diagnostic = createDiagnostic({
      code: DIAGNOSTIC_CODES.TRAILING_WHITESPACE,
      lineIndex: 0,
      startColumn: "NODE_VERSION := 22".length,
      endColumn: "NODE_VERSION := 22   ".length,
    });

    const action = getQuickFix(
      document,
      diagnostic,
      "Remove trailing whitespace",
    );

    await applyQuickFix(action);

    assert.strictEqual(document.getText(), "NODE_VERSION := 22\n");
  });

  test("keeps one blank line when removing multiple blank lines between sections", async () => {
    const document = await createMakefileDocument("A := 1\n\n\nB := 2\n");

    const diagnostic = createDiagnostic({
      code: DIAGNOSTIC_CODES.MULTIPLE_BLANK_LINES,
      lineIndex: 2,
      startColumn: 0,
      endColumn: 0,
    });

    const action = getQuickFix(
      document,
      diagnostic,
      "Remove extra blank lines",
    );

    await applyQuickFix(action);

    assert.strictEqual(document.getText(), "A := 1\n\nB := 2\n");
  });

  test("removes all blank lines between target and recipe when fixing multiple blank lines", async () => {
    const document = await createMakefileDocument("test:\n\n\n\tnvm install\n");

    const diagnostic = createDiagnostic({
      code: DIAGNOSTIC_CODES.MULTIPLE_BLANK_LINES,
      lineIndex: 2,
      startColumn: 0,
      endColumn: 0,
    });

    const action = getQuickFix(
      document,
      diagnostic,
      "Remove extra blank lines",
    );

    await applyQuickFix(action);

    assert.strictEqual(document.getText(), "test:\n\tnvm install\n");
  });

  test("adds missing final newline", async () => {
    const document = await createMakefileDocument("A := 1");

    const diagnostic = createDiagnostic({
      code: DIAGNOSTIC_CODES.MISSING_FINAL_NEWLINE,
      lineIndex: 0,
      startColumn: "A := 1".length,
      endColumn: "A := 1".length,
    });

    const action = getQuickFix(document, diagnostic, "Add final newline");

    await applyQuickFix(action);

    assert.strictEqual(document.getText(), "A := 1\n");
  });

  test("removes blank line before recipe command", async () => {
    const document = await createMakefileDocument("test:\n\n\tnvm install\n");

    const diagnostic = createDiagnostic({
      code: DIAGNOSTIC_CODES.BLANK_LINE_BEFORE_RECIPE_COMMAND,
      lineIndex: 1,
      startColumn: 0,
      endColumn: 0,
    });

    const action = getQuickFix(
      document,
      diagnostic,
      "Remove blank lines before recipe command",
    );

    await applyQuickFix(action);

    assert.strictEqual(document.getText(), "test:\n\tnvm install\n");
  });
});

/**
 * Creates an in-memory Makefile document for quick fix tests.
 *
 * The document is not written to disk. It is opened through the VS Code API so
 * the quick fix provider can work with a real TextDocument instance.
 */
async function createMakefileDocument(
  content: string,
): Promise<vscode.TextDocument> {
  return vscode.workspace.openTextDocument({
    content,
    language: "makefile",
  });
}

/**
 * Parameters used to create a test diagnostic.
 */
interface CreateDiagnosticParams {
  code: DiagnosticCode;
  lineIndex: number;
  startColumn: number;
  endColumn: number;
}

/**
 * Creates a diagnostic matching the structure expected by the quick fix
 * provider.
 *
 * The message itself is not relevant for these tests. The diagnostic code and
 * range are the important values used to select and apply the correct fix.
 */
function createDiagnostic({
  code,
  lineIndex,
  startColumn,
  endColumn,
}: CreateDiagnosticParams): vscode.Diagnostic {
  const diagnostic = new vscode.Diagnostic(
    new vscode.Range(lineIndex, startColumn, lineIndex, endColumn),
    "Test diagnostic",
    vscode.DiagnosticSeverity.Warning,
  );

  diagnostic.code = code;

  return diagnostic;
}

/**
 * Gets a quick fix action by title for a given diagnostic.
 *
 * This helper invokes the provider directly and ensures that the expected
 * CodeAction is available before the test tries to apply it.
 */
function getQuickFix(
  document: vscode.TextDocument,
  diagnostic: vscode.Diagnostic,
  title: string,
): vscode.CodeAction {
  const provider = new WhitespaceQuickFixProvider();

  const context: vscode.CodeActionContext = {
    diagnostics: [diagnostic],
    only: vscode.CodeActionKind.QuickFix,
    triggerKind: vscode.CodeActionTriggerKind.Invoke,
  };

  const actions = provider.provideCodeActions(
    document,
    diagnostic.range,
    context,
  );

  const action = actions.find((item) => item.title === title);

  assert.ok(action, `Expected quick fix "${title}" to be available.`);

  return action;
}

/**
 * Applies the WorkspaceEdit from a quick fix action.
 *
 * The assertion guarantees that the action contains an edit and that VS Code
 * successfully applies it to the current document.
 */
async function applyQuickFix(action: vscode.CodeAction): Promise<void> {
  assert.ok(
    action.edit,
    `Expected quick fix "${action.title}" to have an edit.`,
  );

  const applied = await vscode.workspace.applyEdit(action.edit);

  assert.strictEqual(
    applied,
    true,
    `Expected quick fix "${action.title}" edit to be applied.`,
  );
}
